# Generated by Django 5.2.5 on 2025-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('home_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('knowledge_title', models.CharField(default='Don’t Just Gain info', max_length=200)),
                ('knowledge_highlight', models.CharField(default='Build Knowledge', max_length=200)),
                ('knowledge_description', models.TextField(default='Whether you’re a new investor or a market expert, we’ve got something for everyone at the TRACO blog')),
                ('knowledge_blog_name', models.CharField(default='TRACO', max_length=50)),
                ('knowledge_image', models.ImageField(blank=True, null=True, upload_to='knowledge/')),
            ],
        ),
    ]
