# Generated by Django 5.2.5 on 2025-09-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='knowledge_image',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='knowledge_blog_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='knowledge_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='knowledge_highlight',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='knowledge_title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('read_time', models.CharField(help_text="e.g. '5 Mins Read'", max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tradingapp.category')),
            ],
        ),
    ]
