# Generated by Django 5.2.5 on 2025-09-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0003_footermenu_footersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='facebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
    ]
