# Generated by Django 5.2.5 on 2025-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='home_banner/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='home_banner/')),
                ('small_text', models.CharField(default='Keep Your Money Safe !!!!', max_length=200)),
                ('title', models.CharField(default='Build Confidence With Every Single Trade.', max_length=200)),
                ('subtitle', models.CharField(default='Invest for Your Future', max_length=200)),
                ('description', models.CharField(default='Your Trading Journey Started Here....', max_length=300)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('users_count', models.CharField(default='500+ Realtime Users', max_length=50)),
                ('user1', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user2', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user3', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user4', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user5', models.ImageField(blank=True, null=True, upload_to='users/')),
            ],
        ),
    ]
