# Generated by Django 5.2.5 on 2025-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0006_homebanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='background',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='small_text',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='button_link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='highlight',
            field=models.CharField(default='Invest for Your Future', max_length=300),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='users_label',
            field=models.CharField(default='Realtime Users', max_length=100),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='button_text',
            field=models.CharField(default='Start Now', max_length=100),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='description',
            field=models.TextField(default='Your Trading Journey Started Here....'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='subtitle',
            field=models.CharField(default='Keep Your Money Safe !!!!', max_length=200),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(default='Build Confidence With Every Single Trade.', max_length=300),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='user1',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='user2',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='user3',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='user4',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='user5',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='users_count',
            field=models.CharField(default='500+', max_length=50),
        ),
    ]
