# Generated by Django 5.2.5 on 2025-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0007_remove_homebanner_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='section_backgrounds/')),
            ],
        ),
    ]
