# Generated by Django 5.2.5 on 2025-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0009_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 01, 02, 03', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False, help_text='Highlight this column in green?')),
            ],
        ),
    ]
