# Generated by Django 5.2.5 on 2025-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0010_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('position', models.PositiveIntegerField(help_text='Order of step (1,2,3,4)')),
                ('image', models.ImageField(blank=True, help_text='Optional icon image', null=True, upload_to='howitworks/')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
