# Generated by Django 5.2.5 on 2025-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0011_howitworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(help_text='Background image for How it Works section', upload_to='howitworks_bg/')),
            ],
        ),
    ]
