# Generated by Django 5.2.5 on 2025-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0012_howitworkssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='dashboard_backgrounds/')),
            ],
        ),
    ]
