# Generated by Django 5.2.5 on 2025-09-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0013_dashboardbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of image display (1,2,3,...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tradingapp.communitysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
