# Generated by Django 5.2.5 on 2025-09-05 12:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0015_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About TRACO', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]




