# Generated by Django 5.2.5 on 2025-09-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0016_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
