# Generated by Django 5.2.5 on 2025-09-05 13:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0017_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who are We?', max_length=200)),
                ('intro', models.TextField(help_text='Intro paragraph under title')),
                ('intro_secondary', models.TextField(blank=True, help_text='Second intro paragraph')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField()),
                ('image', models.ImageField(help_text='Team image', upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]