# Generated by Django 5.2.5 on 2025-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0018_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='about_icons/')),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
            },
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='intro_secondary',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(max_length=200),
        ),
    ]
