# Generated by Django 5.2.5 on 2025-09-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0019_aboutfeature_alter_aboutpage_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
