# Generated by Django 5.2.5 on 2025-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0020_partnerenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the partner section', max_length=255)),
                ('highlight', models.CharField(help_text='Highlighted word (e.g., TRACO)', max_length=50)),
                ('sub_text', models.TextField(help_text='Text shown below the form')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(help_text='Left side image', upload_to='partner/')),
            ],
        ),
    ]
