# Generated by Django 5.2.5 on 2025-09-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0021_partnerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
                ('heading', models.CharField(default='Welcome to the First Step of Becoming a TRACO Partner', max_length=255)),
                ('contact_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradingapp.partnercity')),
            ],
        ),
        migrations.DeleteModel(
            name='PartnerEnquiry',
        ),
        migrations.DeleteModel(
            name='PartnerPage',
        ),
    ]
