# Generated by Django 5.2.5 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0022_partnercity_partnerpagecontent_partnerrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='partner/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlighted', models.BooleanField(default=True)),
            ],
        ),
    ]
