# Generated by Django 5.2.5 on 2025-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0023_partnerbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('login', 'Login Page'), ('register', 'Register Page')], max_length=20)),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth_pages/')),
            ],
        ),
    ]
